export const footers={
    "Загрузить":{
        caption:"Или выберите документ",
        ionic:"cloud-upload-outline"
    },
    "Скачать":{
        caption:"Или скачайте перевод",
        ionic:"cloud-download-outline"
    }
} as  const;
export const languages =
    {
        "auto": { "name": "Auto", "native": "Detect" },
        "af": { "name": "Afrikaans", "native": "Afrikaans" },
        "sq": { "name": "Albanian", "native": "Shqip" },
        "ar": { "name": "Arabic", "native": "عربي" },
        "hy": { "name": "Armenian", "native": "Հայերէն" },
        "az": { "name": "Azerbaijani", "native": "آذربایجان دیلی" },
        "eu": { "name": "Basque", "native": "Euskara" },
        "be": { "name": "Belarusian", "native": "Беларуская" },
        "bg": { "name": "Bulgarian", "native": "Български" },
        "ca": { "name": "Catalan", "native": "Català" },
        "zh-CN": { "name": "Chinese (Simplified)", "native": "中文简体" },
        "zh-TW": { "name": "Chinese (Traditional)", "native": "中文繁體" },
        "hr": { "name": "Croatian", "native": "Hrvatski" },
        "cs": { "name": "Czech", "native": "Čeština" },
        "da": { "name": "Danish", "native": "Dansk" },
        "nl": { "name": "Dutch", "native": "Nederlands" },
        "en": { "name": "English", "native": "English" },
        "et": { "name": "Estonian", "native": "Eesti keel" },
        "tl": { "name": "Filipino", "native": "Filipino" },
        "fi": { "name": "Finnish", "native": "Suomi" },
        "fr": { "name": "French", "native": "Français" },
        "gl": { "name": "Galician", "native": "Galego" },
        "ka": { "name": "Georgian", "native": "ქართული" },
        "de": { "name": "German", "native": "Deutsch" },
        "el": { "name": "Greek", "native": "Ελληνικά" },
        "ht": { "name": "Haitian Creole", "native": "Kreyòl ayisyen" },
        "iw": { "name": "Hebrew", "native": "עברית" },
        "hi": { "name": "Hindi", "native": "हिन्दी" },
        "hu": { "name": "Hungarian", "native": "Magyar" },
        "is": { "name": "Icelandic", "native": "Íslenska" },
        "id": { "name": "Indonesian", "native": "Bahasa Indonesia" },
        "ga": { "name": "Irish", "native": "Gaeilge" },
        "it": { "name": "Italian", "native": "Italiano" },
        "ja": { "name": "Japanese", "native": "日本語" },
        "ko": { "name": "Korean", "native": "한국어" },
        "lv": { "name": "Latvian", "native": "Latviešu" },
        "lt": { "name": "Lithuanian", "native": "Lietuvių kalba" },
        "mk": { "name": "Macedonian", "native": "Македонски" },
        "ms": { "name": "Malay", "native": "Malay" },
        "mt": { "name": "Maltese", "native": "Malti" },
        "no": { "name": "Norwegian", "native": "Norsk" },
        "fa": { "name": "Persian", "native": "فارسی" },
        "pl": { "name": "Polish", "native": "Polski" },
        "pt": { "name": "Portuguese", "native": "Português" },
        "ro": { "name": "Romanian", "native": "Română" },
        "ru": { "name": "Russian", "native": "Русский" },
        "sr": { "name": "Serbian", "native": "Српски" },
        "sk": { "name": "Slovak", "native": "Slovenčina" },
        "sl": { "name": "Slovenian", "native": "Slovensko" },
        "es": { "name": "Spanish", "native": "Español" },
        "sw": { "name": "Swahili", "native": "Kiswahili" },
        "sv": { "name": "Swedish", "native": "Svenska" },
        "th": { "name": "Thai", "native": "ไทย" },
        "tr": { "name": "Turkish", "native": "Türkçe" },
        "uk": { "name": "Ukrainian", "native": "Українська" },
        "ur": { "name": "Urdu", "native": "اردو" },
        "vi": { "name": "Vietnamese", "native": "Tiếng Việt" },
        "cy": { "name": "Welsh", "native": "Cymraeg" },
        "yi": { "name": "Yiddish", "native": "ייִדיש" }
    };

export const bins ={
    "10":{ "name": "Десятичная", "native": "decimal" },
    "2":{ "name": "Двоичная", "native": "bin" },
    "8":{ "name": "Восьмеричная", "native": "oct" },
    "16":{ "name": "Шестнадцатиричная", "native": "hex" },
};